---
- name: Install java and net-tools
  hosts: 178.128.146.37
  tasks:
    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install Java 8
      apt: name=openjdk-8-jre-headless
    - name: Install net-tools
      apt: name=net-tools

- name: Download and unpack Nexus installer
  hosts: 178.128.146.37
  tasks:
    - name: Check nexus folder stats
      stat:
        path: /opt/nexus
      register: stat_result
    - name: Download Nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
    - name: Untar Nexus installer
      unarchive:
        src: /opt/nexus-3.75.1-01-unix.tar.gz
        dest: /opt/
        remote_src: yes

