---
- name: Install node and npm
  hosts: 157.230.5.162 
  tasks:
   - name: Update apt repo and cache
     apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
   - name: Install nodejs and npm
     apt:
        pkg: 
          - nodejs
          - npm


- name: Create new linux user for node app
  # replace with your host IP address
  hosts: 157.230.5.162
  vars_files:
    project-vars
  tasks:
    - name: Create linux user
      user:
      # replace with your username
        name: "{{linux_name}}"
        comment: Node User
        group: admin

- name: Deploy nodejs app
  hosts: 157.230.5.162
  become: True
  become_user: "{{linux_name}}"
  vars_files:
    project-vars
  tasks: 
    - name: Copy nodejs folder to a server
      copy:
        src: "{{location}}/nodejs-app-{{version}}.tgz"
        dest: "{{user_home_dir}}/app-1.0.0.tgz"
    - name: Unpack the nodejs file
      unarchive:
        src: "{{user_home_dir}}/app-1.0.0.tgz"
        dest: "{{user_home_dir}}"
        remote_src: yes
      
    - name: Install dependencies
      npm:
        path: "{{user_home_dir}}/package"
    - name: Start the application
      command: 
        chdir: "{{user_home_dir}}/package/app"
        cmd: node server
      async: 1000
      poll: 0
    - name: Ensure app is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{app_status.stdout_lines}}


